# NumPy Arrays

In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list) # cast a normal python list to a numpy array

array([1, 2, 3])

In [5]:
arr=np.array(my_list)  # 1D array

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)  # 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0,11,2)  # adding a step size

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)  # 1 number as 1D array

array([ 0.,  0.,  0.])

In [18]:
np.zeros((5,5))  # tuples as 2D array

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.ones(4) # number as 1D array

array([ 1.,  1.,  1.,  1.])

In [17]:
np.ones((3,4))  # tuples as 2D array

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [20]:
np.linspace(0,5,11)  # DON'T GET CONFUSED WITH linspace with arange

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [22]:
np.eye(4)  # identity matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [23]:
np.random.rand(5)  # uniform distribution between 0 and 1

array([ 0.51925156,  0.12827601,  0.88162898,  0.70588188,  0.15464326])

In [24]:
np.random.rand(5,5)  # 2D array, use two args instead of tuples

array([[ 0.18926806,  0.29255222,  0.75770452,  0.03635712,  0.55410036],
       [ 0.67809979,  0.39042286,  0.80684084,  0.63488206,  0.26726403],
       [ 0.65987312,  0.13098269,  0.83392879,  0.42343918,  0.36178007],
       [ 0.14545704,  0.25791454,  0.05633321,  0.15684255,  0.08417805],
       [ 0.06073005,  0.62317172,  0.48713924,  0.38206082,  0.83600362]])

In [25]:
np.random.randn(2)  # return standard normal distribution

array([-0.90583008,  0.95785715])

In [27]:
np.random.randn(4,4) 

array([[-0.45297043,  1.09911041,  1.22415002,  0.02610042],
       [ 0.87535495,  1.96294059,  0.02550976,  1.52047018],
       [ 0.83295931,  1.57805906,  0.13081776, -0.25126972],
       [ 0.28032102, -0.544695  , -0.23782706, -1.22440086]])

In [29]:
np.random.randint(1,100)  # Return random integers from `low` (inclusive) to `high` (exclusive).


8

In [30]:
np.random.randint(1,100,10) 

array([47, 97,  6, 77, 88, 59, 50, 77, 89, 38])

In [31]:
arr=np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr=np.random.randint(0,50,10)

In [34]:
ranarr

array([ 2, 34, 35, 40, 40,  3, 48, 26,  1,  8])

In [35]:
# reshape()

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr.max()

48

In [39]:
ranarr.min()

1

In [40]:
ranarr.argmax()  # index location of the max value

6

In [41]:
ranarr.argmin()

8

In [43]:
arr.shape  # check the dimention of the numpy array

(25,)

In [44]:
arr.reshape(5,5).shape

(5, 5)

In [45]:
# data type of the array

In [46]:
arr.dtype

dtype('int32')

In [49]:
from numpy import random

In [58]:
random.randint(2,10)

8

In [51]:
from numpy.random import randint

In [55]:
randint(2,10)

6